services:
  mysql:
    image: mysql:8.4
    container_name: support-ai-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: support_ai_saas
      MYSQL_USER: support_ai
      MYSQL_PASSWORD: support_ai_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
